botApiToken: "MTAxMDAyOTc5OTM0MDc3MzQ2Nw.GZhlg0.6UMcGaOitfOhBDylXh4JiIDWWH4AWsnZlNIkrM"
botActivityType: "WATCHING" # (COMPETING, LISTENING, PLAYING, STREAMING, WATCHING)
botActivityDescription: "taters"